export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'

export const GET_ALL_LOCATION = 'GET_ALL_LOCATION'

export const ORDER_BY_DATE = 'ORDER_BY_DATE'


export const PROJECTS = 'PROJECTS'
export const DOCUMENTARYS = 'DOCUMENTARYS'
export const ARTICLES = 'ARTICLES'