
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const GET_ALL_LOCATION = 'GET_ALL_LOCATION'
export const GET_ARTICLES = 'GET_ARTICLES'


export const PROJECTS = 'PROJECTS'
export const DOCUMENTARYS = 'DOCUMENTARYS'
export const ARTICLES = 'ARTICLES'

export const ORDER_BY_DATE = 'ORDER_BY_DATE'

export const GET_BY_INPUT = 'GET_BY_INPUT'
export const POST_NEW_USER = "POST_NEW_USER"
export const POST_NEW_ARTICLE = "POST_NEW_ARTICLE"